# Generated by Django 4.2.5 on 2023-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='product_belong',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
