# Generated by Django 4.2.5 on 2023-09-23 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_lesson_video_lesson_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson_progress',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 8, 52, 8, 103884, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(related_name='products', to='polls.lesson'),
        ),
    ]
