# Generated by Django 4.2.5 on 2023-09-23 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_lessonprogress_lesson_progress_alter_product_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_viewed', models.IntegerField(help_text='duration in seconds')),
                ('lesson_status', models.BooleanField(default=False)),
                ('lesson_progress', models.DateTimeField(default=datetime.datetime(2023, 9, 23, 9, 12, 14, 373003, tzinfo=datetime.timezone.utc))),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='polls.lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
